import { Video, User, Comment } from './types';

// Mock users
export const mockUsers: Record<string, User> = {
  user1: {
    id: 'user1',
    username: '@cryptomastery',
    email: 'crypto@tech.com',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=cryptomastery',
    bio: 'Blockchain educator & crypto pioneer',
    createdAt: new Date(2024, 0, 15).toISOString(),
  },
  user2: {
    id: 'user2',
    username: '@electronicslab',
    email: 'lab@tech.com',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=electronicslab',
    bio: 'DIY electronics enthusiast',
    createdAt: new Date(2024, 1, 10).toISOString(),
  },
  user3: {
    id: 'user3',
    username: '@devtutorials',
    email: 'dev@tech.com',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=devtutorials',
    bio: 'Full-stack development tutorials',
    createdAt: new Date(2024, 2, 5).toISOString(),
  },
  user4: {
    id: 'user4',
    username: '@hardwaregeek',
    email: 'hardware@tech.com',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=hardwaregeek',
    bio: 'Latest hardware reviews & benchmarks',
    createdAt: new Date(2024, 2, 20).toISOString(),
  },
};

// Mock videos
export const mockVideos: Video[] = [
  {
    id: 'vid1',
    userId: 'user1',
    title: 'Understanding Bitcoin Smart Contracts in 2024',
    description: 'Learn how Bitcoin smart contracts work and their latest developments',
    thumbnailUrl: '/placeholder.svg?height=400&width=600',
    videoUrl: 'https://www.youtube.com/embed/j0l5k0l5k',
    category: 'crypto-blockchain',
    viewCount: 45230,
    likeCount: 2150,
    commentCount: 312,
    createdAt: new Date(2024, 3, 1).toISOString(),
    user: mockUsers.user1,
  },
  {
    id: 'vid2',
    userId: 'user2',
    title: 'Building a DIY IoT Weather Station',
    description: 'Complete guide to building your own IoT weather station from scratch',
    thumbnailUrl: '/placeholder.svg?height=400&width=600',
    videoUrl: 'https://www.youtube.com/embed/weather123',
    category: 'electronics-diy',
    viewCount: 23450,
    likeCount: 1890,
    commentCount: 245,
    createdAt: new Date(2024, 2, 28).toISOString(),
    user: mockUsers.user2,
  },
  {
    id: 'vid3',
    userId: 'user3',
    title: 'Next.js 15 Advanced Patterns',
    description: 'Master the latest Next.js patterns for production applications',
    thumbnailUrl: '/placeholder.svg?height=400&width=600',
    videoUrl: 'https://www.youtube.com/embed/nextjs456',
    category: 'software-dev',
    viewCount: 67890,
    likeCount: 4230,
    commentCount: 562,
    createdAt: new Date(2024, 2, 25).toISOString(),
    user: mockUsers.user3,
  },
  {
    id: 'vid4',
    userId: 'user4',
    title: 'RTX 5090 vs RTX 4090 Detailed Comparison',
    description: 'In-depth performance analysis of the latest GPU generation',
    thumbnailUrl: '/placeholder.svg?height=400&width=600',
    videoUrl: 'https://www.youtube.com/embed/gpu789',
    category: 'hardware-reviews',
    viewCount: 98765,
    likeCount: 5640,
    commentCount: 812,
    createdAt: new Date(2024, 2, 22).toISOString(),
    user: mockUsers.user4,
  },
  {
    id: 'vid5',
    userId: 'user1',
    title: 'Ethereum Layer 2 Solutions Explained',
    description: 'Deep dive into L2 scaling solutions and their implications',
    thumbnailUrl: '/placeholder.svg?height=400&width=600',
    videoUrl: 'https://www.youtube.com/embed/eth234',
    category: 'crypto-blockchain',
    viewCount: 54320,
    likeCount: 3210,
    commentCount: 425,
    createdAt: new Date(2024, 2, 20).toISOString(),
    user: mockUsers.user1,
  },
  {
    id: 'vid6',
    userId: 'user3',
    title: 'React 19 Compiler Deep Dive',
    description: 'Understanding the new React compiler and its optimization benefits',
    thumbnailUrl: '/placeholder.svg?height=400&width=600',
    videoUrl: 'https://www.youtube.com/embed/react19',
    category: 'software-dev',
    viewCount: 76540,
    likeCount: 4890,
    commentCount: 634,
    createdAt: new Date(2024, 2, 18).toISOString(),
    user: mockUsers.user3,
  },
];

export const mockComments: Comment[] = [
  {
    id: 'comment1',
    userId: 'user2',
    videoId: 'vid1',
    text: 'Great explanation! Finally understand how this works.',
    createdAt: new Date(2024, 3, 2).toISOString(),
    user: mockUsers.user2,
  },
  {
    id: 'comment2',
    userId: 'user3',
    videoId: 'vid1',
    text: 'More videos like this please!',
    createdAt: new Date(2024, 3, 2).toISOString(),
    user: mockUsers.user3,
  },
];
